hw2

diff --git a/hw2/cx b/hw2/cx
--- a/hw2/cx
+++ b/hw2/cx
@@ -1,7 +1,8 @@
 #!/bin/bash
 
-if chmod +x "$@"; then
-    exit 0
+if [ $# -eq 0 ]; then
+    echo "ERROR: no argument given"
+    exit 1
 else
-    echo "ERROR: "
+    chmod +x "$@"
 fi
