finish hw2

diff --git a/hw2/howmany b/hw2/howmany
--- a/hw2/howmany
+++ b/hw2/howmany
@@ -1,3 +1,8 @@
 #!/bin/bash
 
-./whoson | wc -w
+if [ $# -ne 0 ]; then
+    echo "ERROR: invalid argument given"
+    exit 1
+else
+    ./whoson | wc -w
+fi
diff --git a/hw2/lss b/hw2/lss
--- a/hw2/lss
+++ b/hw2/lss
@@ -1,3 +1,8 @@
 #!/bin/bash
 
-ls -lS
+if [ $# -ne 0 ]; then
+    echo "ERROR: invalid argument given"
+    exit 1
+else
+    ls -lS | tail -n +2
+fi
diff --git a/hw2/nf b/hw2/nf
--- a/hw2/nf
+++ b/hw2/nf
@@ -1,3 +1,8 @@
 #!/bin/bash
 
-ls -1 | wc -l
+if [ $# -ne 0 ]; then
+    echo "ERROR: invalid argument given"
+    exit 1
+else
+    ls -1 | wc -l
+fi
diff --git a/hw2/valid b/hw2/valid
--- a/hw2/valid
+++ b/hw2/valid
@@ -1,3 +1,11 @@
 #!/bin/bash
 
-(echo $1 | grep -q '^[a-zA-Z_][a-zA-Z0-9_]*$') && echo 'yes' || echo 'no'
+if [ $# -eq 0 ]; then
+    echo "ERROR: no argument given"
+    exit 1
+elif [ $# -ne 1 ]; then
+    echo "ERROR: invalid number of argument(s) given"
+    exit 1
+else
+    (echo "$1" | grep -q '^[a-zA-Z_][a-zA-Z0-9_]*$') && echo 'yes' || echo 'no'
+fi
diff --git a/hw2/whoson b/hw2/whoson
--- a/hw2/whoson
+++ b/hw2/whoson
@@ -1,3 +1,8 @@
 #!/bin/bash
 
-echo $(groups $(users) | grep ugrad | cut -d: -f1 | sort -u | tr -d '\n')
+if [ $# -ne 0 ]; then
+    echo "ERROR: invalid argument given"
+    exit 1
+else
+    echo $(groups $(users) | grep ugrad | cut -d: -f1 | sort -u | tr -d '\n')
+fi
